= My Curriculum Vitae/Resume

image:https://travis-ci.com/dduportal/cv.svg?branch=master["Build Status", link="https://travis-ci.com/dduportal/cv"]

This repository contains my curriculum vitae.

== Why

As a software engineer, I wanted my CV to follow my professional practices :

* Source text based to easily use SCMs, merging, diffing, history
* Publicly available, shareable, editable
* HTML W3C compliant but also PDF format to ease reading

== What

* Content of the CV is written in link:https://asciidoctor.org/[Asciidoctor],
which allows output to both HTML and PDF.

* Continous Deployment is done with link:https://travis-ci.com/[Travis],
which generates the HTML and PDF outputs, validate them and deploy them.

* Deployment is done in link:https://pages.github.com/[Github Pages].

== How

=== Requirements

* Make
* Docker and Docker-Compose

=== Build

Run the following commands to:

* Build all the outputs:
+
[source,bash]
----
make build
----

* Build the HTML output:
+
[source,bash]
----
make html
----


* Build the PDF output:
+
[source,bash]
----
make pdf
----

// === Local

// Open you browser to the page, using your Docker Engine IP :

// ```text
// http://<YOUR DOCKER ENGINE IP>:4000
// ```

== Licensing

This repository is provided on the link:http://www.gnu.org/licenses/license-list.html#ISC[ISC license].

You will find the License link:./LICENSE.adoc[here].

It means you can use the content only
if you make it appear with the same license.
